### ISSUE TITLE
Detect Prometheus also by HTTP Headers

### ISSUE THREAD

**Issue by bastischubert** [fhemberger/chrome-prometheus-formatter#1]
Hi,

"text/plain; version=0.0.4" could also be a good marker for detecting prometheus output instead of relying on /metrics or other path informations

source: https://prometheus.io/docs/instrumenting/exposition_formats/

@RichiH

**Comment by fhemberger** [comment]
Hi, unfortunately I don't have access to headers in the Chrome extension.

**Comment by fhemberger** [comment]
I'm closing this for now. prometheus-formatter will only honor `text/plain`and `application/openmetrics-text` content types. For now I won't check explicitly for a version number in the header as some exporters might not provide it.

For `text/plain` I'll still limit parsing to the defined metric endpoints, while this setting will be ignored for `application/openmetrics-text`.
