### ISSUE TITLE
Not working in Ubuntu 20.04.2 LTS in /metrics

### ISSUE THREAD

**Issue by Knautiluz** [fhemberger/chrome-prometheus-formatter#13]
O.S: Ubuntu 20.04.2 LTS
Chrome Version: 90.0.4430.93 64 bits
Endpoint with error: http://localhost:4000/metrics
Paths treated as prom endpoints:
```
^/metrics
^/federate
^/probe
^/prometheus
^/actuator/prometheus
```
- Tested with all extensions enabled
- Tested with all extensions disabled, and only left prom extension enabled

Result is a plain text without formatation like
```# HELP graphql_queries_parsed The amount of GraphQL queries that have been parsed. # TYPE graphql_queries_parsed counter # HELP graphql_queries_validation_started The amount of GraphQL queries that have started validation. # TYPE graphql_queries_validation_started counter # HELP graphql_queries_resolved The amount of GraphQL queries that have had their operation resolved. # TYPE graphql_queries_resolved counter # HELP graphql_queries_execution_started The amount of GraphQL queries that have started executing. # TYPE graphql_queries_execution_started counter # HELP graphql_queries_errored The amount of GraphQL queries that have encountered errors. # TYPE graphql_queries_errored counter # HELP graphql_queries_responded The amount of GraphQL queries that have been executed and been attempted to send to the client. This includes requests with errors. # TYPE graphql_queries_responded counter # HELP graphql_resolver_time The time to resolve a GraphQL field. # TYPE graphql_resolver_time histogram # HELP graphql_total_request_time The time to complete a GraphQL query. # TYPE graphql_total_request_time histogram```

**Comment by Knautiluz** [comment]
Worked now using: `'content-type', 'text/plain'`, was my mistake.

**Comment by fhemberger** [comment]
Yes, Prometheus metrics are always `text/plain` by spec:
https://prometheus.io/docs/instrumenting/exposition_formats/

Thanks for updating your extension review!
