### ISSUE TITLE
Need support other metrics endpoints

### ISSUE THREAD

**Issue by imclint21** [fhemberger/chrome-prometheus-formatter#20]
Hi,

Nice extension guys!

Anyway, by example I'm running http://localhost/snmp and the metrics are not formatted, I guess there are a better away to parse and detect prometheus metrics

Regards

**Comment by fhemberger** [comment]
Hi,

great to hear you find the extension useful. If you click on its icon, you can define additional paths for highlighting.

(Metric endpoints usually serve the data with a `text/plain` mime type, but sending *all* plain text files through the parser doesn't make much sense.)

**Comment by imclint21** [comment]
Hi,

Ah I see, I thought about this, I went in extension settings but didn't found parsing settings, now I see it, thanks!

Anyway, I tried to add ^/snmp and other regex, but nothing seems works..

This is the endpoint I try to add, I guess I should also specify the path.

http://10.1.0.2:9116/snmp?module=if_mib&target=10.1.0.6

**Comment by imclint21** [comment]
Ah nevermind, now it works like a charm, just added `^/snmp` I guess it was not saved before or whatever!

<img width="627" alt="image" src="https://github.com/fhemberger/prometheus-formatter/assets/5221349/bd5a79d6-cbc4-4613-9939-a4259869d1dd">
