### ISSUE TITLE
 hide metrics with 0 value

### ISSUE THREAD

**Issue by yarda7** [fhemberger/chrome-prometheus-formatter#21]
Hi @fhemberger 
Thanks for the great extension, it's my favorite...

I am writing to you not about accessibility issues, but a great idea for improvement.
Any chance to easily hide(or filter) metrics with 0 value?
Hope you find this idea as useful.
 
Thanks.
Best Regards,
Jarda

**Comment by fhemberger** [comment]
Hi Jarda,

thanks for your feedback. I don't plan to add metric filtering, it would be too complex to handle various cases/filter queries and the extension is solely meant to quickly check metric endpoints. Instead, I'd recommend to temporarily add the metric endpoint to a Prometheus instance and use PromQL for filtering.

However, feel free to fork this extension for your use case, the code for the metric output is [here](https://github.com/fhemberger/prometheus-formatter/blob/main/extension/js/background.js#L38-L49). You can run the modified code directly in your browser:

* **Google Chrome** or **Microsoft Edge**:
  * Go to `chrome://extensions/` respectively `edge://extensions/`,
  * enable "Developer mode",
  * click "Load unpacked extension",
  * select the `extension` folder in this repo.
* **Firefox**:
  * Go to `about:addons`
  * From the Cog-Menu on the right choose "Install Add-On From File …"
