### ISSUE TITLE
New version bugged - no file found

### ISSUE THREAD

**Issue by melkorm** [fhemberger/chrome-prometheus-formatter#5]
New version doesn't contains html files, I think the reason is due release script:

https://github.com/fhemberger/chrome-prometheus-formatter/blob/master/package.json#L7 :
```
    "release": "cd extension && zip -r ../chrome-webstore-release.zip icons js LICENSE.txt manifest.json -x icons/.DS_Store js/.DS_Store .DS_Store"
```

I think html folder is missing 🤔 

@fhemberger could you look into this ? I have never published chrome extensions and I think it will be faster for you to fix it :)

**Comment by fhemberger** [comment]
Whoops, fixed! Released `v1.2.2`
